config/routes.rb
Rails.application.routes.draw do
  devise_for :user_apis
  resources :challenges
  get 'welcome/index'
  get 'profile', to: 'users#edit'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'search', to: 'articles#search'
  get 'like_article', to: 'articles#like'
  root 'welcome#index'
  get 'weather', to: 'weather#index'
  get 'weather_search', to: 'weather#weather_search'
  resources :users
  resources :articles do
    resources :comments
  end

  resources :courses do
    resources :topics do
      resources :challenges do
        get 'challenge_submit', to: 'challenges#challenge_submit'
      end
    end 
  end

  namespace :api do
    namespace :v1 do
      resources :articles do 
        resources :comments, only: [:create, :index]
      end 
      resources :users
      post "/auth/login", to: "authentication#login"
      resources :courses
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy 
    has_rich_text :description
    has_one_attached :logo
    has_one_attached :banner
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10, maximum:250 } 
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :topic
end

app/models/challenge_log.rb
class ChallengeLog < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :topics, dependent: :destroy
    has_one_attached :course_logo
    validates :name, presence: true
    validates :description, presence: true
    validates :short_description, presence: true
    validates :level, presence: true
    validates :category, presence: true
    validates :video_url, presence: true
    validates :hours, presence: true
    validates :teacher_name, presence: true
    validates :teacher_description, presence: true

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :challenges, dependent: :destroy
  belongs_to :course
  has_rich_text :topic_notes
end

app/models/topic_log.rb
class TopicLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    has_secure_password
    has_one_attached :avatar

    validates :name, presence: true
    validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
    validates :email, presence: true, uniqueness: true
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Incorrect email format" }
    validates :password, presence: true
    validates :password, length: {minimum: 8 }
end

app/models/user_api.rb
class UserApi < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weather.rb
class Weather < ApplicationRecord
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning Environment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #6351ce !important">
  <div class="container-fluid">
    <a class="navbar-brand" style="color:white" href="/"><b>Learning Environment</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <div class='container'>
          <li class="nav-item" style="margin-top: 3px">  
            <%= link_to('Articles', articles_path, class: 'btn btn-light rounded-pill', style:'color: #1c2331; background-color: white !important') %>
            <%= link_to('Courses', courses_path, class: 'btn btn-light rounded-pill', style:'color:#1c2331; background-color: white !important') %>
            <%= link_to('Weather', weather_path, class: 'btn btn-light rounded-pill', style:'color:#1c2331; background-color: white !important') %>
          </li>  
        </div>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
        
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if name_user(return_user.id).avatar.attached?%>
            <%= image_tag name_user(return_user.id).avatar, height: 35, width: 35, class: "rounded-circle" %>
            <% end %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to('Profile', profile_path, class: 'dropdown-item') %>
            <%= link_to('Create Article', new_article_path, class: 'dropdown-item') %>
            <div class="dropdown-divider"></div>
            <%= link_to('LogOut', logout_path, class: 'dropdown-item') %>
          </div>
        </li> 
        <%else%>
          <li class="nav-item">
            <%= link_to('Login', login_path, class: 'nav-link', style: "font-size: 15px;color: white; margin-top: 9%; font-weight: bold") %>
          </li>
          <li class="nav-item">
            <%= link_to('SignUp', signup_path, class: 'nav-link', style: "font-size: 15px; color: white; margin-top: 8%; font-weight: bold") %>
          </li>  
        <% end %>
      </ul> 
    </div>
  </div>
  </nav>

    <%= yield %>


    <br>
      <!-- Footer -->
      <footer
              class="text-center text-lg-start text-white"
              style="background-color: #1c2331"
              >
        <!-- Section: Social media -->
        <section
                 class="d-flex justify-content-between p-4"
                 style="background-color: #6351ce"
                 >
          <!-- Left -->
          <div class="me-5">
            <span> <b>ENTORNO VIRTUAL DE APRENDIZAJE</b> </span>
          </div>
          <!-- Left -->
    
          <!-- Right -->
          <div>
            <a href="" class="text-white me-4">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="text-white me-4">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="text-white me-4">
              <i class="fab fa-google"></i>
            </a>
            <a href="" class="text-white me-4">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="text-white me-4">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="text-white me-4">
              <i class="fab fa-github"></i>
            </a>
          </div>
          <!-- Right -->
        </section>
        <!-- Section: Social media -->
    
        <!-- Section: Links  -->
        <section class="">
          <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
              <!-- Grid column -->
              <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold">MATEO PRÉSIGA HIDALGO</h6>
                <hr
                    class="mb-4 mt-0 d-inline-block mx-auto"
                    style="width: 60px; background-color: #7c4dff; height: 2px"/>
                <p>
                Student informatic
                </p>
              </div>
              <!-- Grid column -->
    
              <!-- Grid column -->
              <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold">SOCIAL NETWORKS</h6>
                <hr
                    class="mb-4 mt-0 d-inline-block mx-auto"
                    style="width: 60px; background-color: #7c4dff; height: 2px"/>
                <p>
                  <a href="https://www.facebook.com/" target="_blank" class="text-white">Facebook</a>
                </p>
                <p>
                  <a href="https://www.linkedin.com/" target="_blank" class="text-white">Linkedin</a>
                </p>
                <p>
                  <a href="https://github.com/" target="_blank" class="text-white">Github</a>
                </p>
              </div>
    
              <!-- Grid column -->
              
              <!-- Grid column -->
    
              <!-- Grid column -->
              <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold">Contact</h6>
                <hr
                    class="mb-4 mt-0 d-inline-block mx-auto"
                    style="width: 60px; background-color: #7c4dff; height: 2px"
                    />
                <p><i class="fas fa-home mr-3"></i> Colombia, Antioquia, Medellín</p>
                <p><i class="fas fa-envelope mr-3"></i> cpresiga@tdea.edu.co</p>
                <p><i class="fas fa-phone mr-3"></i> + 57 311 684 5279</p>
              </div>
              <!-- Grid column -->
            </div>
            <!-- Grid row -->
          </div>
        </section>
        <!-- Section: Links  -->
    
        <!-- Copyright -->
        <div
             class="text-center p-3"
             style="background-color: rgba(0, 0, 0, 0.2)"
             >
          Licencia: 
          <a class="text-white" href="https://dspace.tdea.edu.co/handle/tda/1"
             >GCC</a
            >
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
  
  </body>
</html>